spring:
  redis:
    #codis: false
    host: localhost
    port: 6379
    #zkHosts: 172.16.10.65:2181,172.16.10.66:2181,172.16.10.67:2181
    #zkDir: /zk/codis/db_codis-w2cx/proxy
  #mail:
    #host: smtp.exmail.qq.com
    #username: 52cx@52cx.com
    #password: '{cipher}0aeec7454073fc5e075a859595fd447694f1b7761d356ca0684587bc82803854'
    #properties:
      #mail:
        #smtp:
          #auth: true
          #starttls:
            #enable: true
            #required: true
  #elastic:
    #clusterName: elasticsearch
    #clusterNodes: 172.16.10.77:9300
  model:
    baseFilePath: E:\\tempFile\\model\\modelFile\\
eureka:
  instance:
    host: localhost
    port: 1111
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: false
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.host}:${eureka.instance.port}/eureka/