spring:
  redis:
    host: localhost
    port: 6379
  model:
    baseFilePath: E:\\tempFile\\model\\modelFile\\
  http:
      multipart:
        enabled: true   # 启用http上传处理
        max-file-size: 100MB # 设置单个文件的最大长度
        max-request-size: 100MB # 设置最大的请求文件的大小
eureka:
  instance:
    host: localhost
    port: 1111
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    healthcheck:
      enabled: false
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.host}:${eureka.instance.port}/eureka/